version: "3"
services:

  mysql:
    image: mysql:5.7
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db_product"
      MYSQL_USER: "product"
      MYSQL_PASSWORD: "product"
    ports:
      - "3306:3306"

  otelcol:
    image: otel/opentelemetry-collector:0.83.0
    network_mode: host
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-config.yml" ]
    volumes:
      - ./opentelemetry/otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - "4317:4317" # OTLP gRPC receiver port
      - "8889:8889" # Promentheus exporter metrics

  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml

  jaeger:
    image: jaegertracing/all-in-one:1.48.0
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "14250:14250"
      - "16686:16686"

  grafana:
    image: grafana/grafana:9.5.8
    container_name: grafana
    ports:
      - "3000:3000"